### ISSUE TITLE
Use the RabbitMQ mgmt api to check for cluster health

### ISSUE THREAD

**Issue by wimpers** [openvstorage/openvstorage-health-check#128]
According to @jeroenmaelbrancke we are using the RabbitMQ mgmt api  to check for the cluster status and health in the support tools. I would make sens to streamline both implementations so the healthcheck also uses the api instead of parsing the logs.

**Comment by jeroenmaelbrancke** [comment]
@kinvaris https://github.com/openvstorage/support-tools/blob/master/ovs/sal/objects/rabbitmq.py#L62

**Comment by wimpers** [comment]
@khenderick @kinvaris @jeroenmaelbrancke  why can't this be 1 single extension that healthcheck  and support tools and all other tools use?

**Comment by jeroenmaelbrancke** [comment]
GIG issue with an older version from the healthcheck.
version: Eugene-updates

Problem:
Rabbitmq node was down.

Not sure if this is covert in the current version from the health check.
```
root@du-conv-1-04:/opt/code/github/0-complexity/openvcloud/libs/agent-scripts/cloudbroker/monitor# python ovs_healthcheck.py 
Traceback (most recent call last):
~ File "ovs_healthcheck.py", line 90, in <module>
print action()
~ File "ovs_healthcheck.py", line 82, in action
check_openvstorage()
~ File "ovs_healthcheck.py", line 62, in check_openvstorage
ovs.checkOvsWorkers()
~ File "/opt/OpenvStorage-healthcheck/openvstorage/openvstoragecluster_health_check.py", line 426, in checkOvsWorkers
if not self._extendedCheckCelery():
~ File "/opt/OpenvStorage-healthcheck/openvstorage/openvstoragecluster_health_check.py", line 382, in _extendedCheckCelery
if int < int(j):
~ ValueError: invalid literal for int() with base 10: "Error: unable to connect to node 'rabbit@du-conv-1-04': nodedown"
type/level: UNKNOWN/1
ValueError: invalid literal for int() with base 10: "Error: unable to connect to node 'rabbit@du-conv-1-04': nodedown"
```

expected something like:
```
[EXCEPTION] unable to connect to node 'rabbit@du-conv-1-04': nodedown
```

**Comment by kinvaris** [comment]
Found another problem:
```
[INFO] Checking model consistency: 
[INFO] Precheck: verification of RabbitMQ cluster: 
[EXCEPTION] Error during execution of the healthcheck
Traceback (most recent call last):
  File "/opt/OpenvStorage/ovs/lib/healthcheck.py", line 35, in <module>
    class HealthCheckController(object):
  File "/opt/OpenvStorage/ovs/lib/healthcheck.py", line 419, in HealthCheckController
    HealthCheckController.run_method(*arguments)
  File "/opt/OpenvStorage/ovs/lib/healthcheck.py", line 367, in run_method
    return HealthCheckController.check_attended()
  File "/usr/lib/python2.7/dist-packages/celery/local.py", line 188, in __call__
    return self._get_current_object()(*a, **kw)
  File "/usr/lib/python2.7/dist-packages/celery/app/task.py", line 420, in __call__
    return self.run(*args, **kwargs)
  File "/opt/OpenvStorage/ovs/lib/healthcheck.py", line 70, in check_attended
    return HealthCheckController.execute_check(unattended, silent_mode)
  File "/usr/lib/python2.7/dist-packages/celery/local.py", line 188, in __call__
    return self._get_current_object()(*a, **kw)
  File "/usr/lib/python2.7/dist-packages/celery/app/task.py", line 420, in __call__
    return self.run(*args, **kwargs)
  File "/opt/OpenvStorage/ovs/lib/healthcheck.py", line 108, in execute_check
    HealthCheckController._check_openvstorage(logger)
  File "/usr/lib/python2.7/dist-packages/celery/local.py", line 188, in __call__
    return self._get_current_object()(*a, **kw)
  File "/usr/lib/python2.7/dist-packages/celery/app/task.py", line 420, in __call__
    return self.run(*args, **kwargs)
  File "/opt/OpenvStorage/ovs/lib/healthcheck.py", line 135, in _check_openvstorage
    OpenvStorageHealthCheck.run(logger)
  File "/opt/OpenvStorage/ovs/extensions/healthcheck/openvstorage/openvstoragecluster_health_check.py", line 579, in run
    OpenvStorageHealthCheck.check_model_consistency(logger)
  File "/opt/OpenvStorage/ovs/extensions/healthcheck/openvstorage/openvstoragecluster_health_check.py", line 491, in check_model_consistency
    partitions = r.partition_status()
  File "/opt/OpenvStorage/ovs/extensions/healthcheck/helpers/rabbitmq.py", line 105, in partition_status
    cluster_status = self.cluster_status()
  File "/opt/OpenvStorage/ovs/extensions/healthcheck/helpers/rabbitmq.py", line 91, in cluster_status
    nodes[node['name']] = {'running': node['running'], 'partitions': node['partitions']}
KeyError: 'partitions'
```

**Comment by kinvaris** [comment]
Fixed issue by https://github.com/openvstorage/openvstorage-health-check/pull/204
