### ISSUE TITLE
Error when using Swift instead of the Alba backend

### ISSUE THREAD

**Issue by matthiasdeblock** [openvstorage/openvstorage-health-check#14]
root@cmp:/opt/OpenvStorage-healthcheck# python ovs_health_check/main.py
Traceback (most recent call last):
  File "ovs_health_check/main.py", line 33, in <module>
    from alba.alba_health_check import AlbaHealthCheck
  File "/opt/OpenvStorage-healthcheck/alba/alba_health_check.py", line 37, in <module>
    from ovs.dal.lists.albabackendlist import AlbaBackendList
ImportError: No module named albabackendlist

**Comment by kinvaris** [comment]
Although this is a feature, it should be caught.
