### ISSUE TITLE
Check module consistency doesn't work

### ISSUE THREAD

**Issue by matthiasdeblock** [openvstorage/openvstorage-health-check#15]
root@cmp:/opt/OpenvStorage-healthcheck# rabbitmqctl cluster_status
Cluster status of node rabbit@cmp ...
[{nodes,[{disc,[rabbit@cmp]}]},{running_nodes,[rabbit@cmp]},{partitions,[]}]
...done.

Traceback (most recent call last):
  File "ovs_health_check/main.py", line 109, in <module>
    Main(unattended)
  File "ovs_health_check/main.py", line 73, in __init__
    self.ovs.checkModelConsistency()
  File "/opt/OpenvStorage-healthcheck/openvstorage/openvstoragecluster_health_check.py", line 642, in checkModelConsistency
    partition_status = cluster_status[3]
IndexError: list index out of range

**Comment by kinvaris** [comment]
Fixed this in https://github.com/openvstorage/openvstorage-health-check/commit/08db99bc0b74358d593be5ab16f83faf3c17c5c2

**Comment by kinvaris** [comment]
merged to stable release01
