### ISSUE TITLE
Disk not found during check dtl

### ISSUE THREAD

**Issue by kinvaris** [openvstorage/openvstorage-health-check#172]
## Problem description
Disk not found during check dtl

## Possible root of the problem
Possible race condition, because sometimes it happens sometimes it does not happen

### Logs
```
root@ovs-node03-1604:~# ovs healthcheck unattended
Traceback (most recent call last):
  File "/opt/OpenvStorage/ovs/lib/healthcheck.py", line 35, in <module>
    class HealthCheckController(object):
  File "/opt/OpenvStorage/ovs/lib/healthcheck.py", line 411, in HealthCheckController
    HealthCheckController.run_method(*arguments)
  File "/opt/OpenvStorage/ovs/lib/healthcheck.py", line 359, in run_method
    return HealthCheckController.check_unattended()
  File "/usr/lib/python2.7/dist-packages/celery/local.py", line 188, in __call__
    return self._get_current_object()(*a, **kw)
  File "/usr/lib/python2.7/dist-packages/celery/app/task.py", line 420, in __call__
    return self.run(*args, **kwargs)
  File "/opt/OpenvStorage/ovs/lib/healthcheck.py", line 54, in check_unattended
    return HealthCheckController.execute_check(unattended, silent_mode)
  File "/usr/lib/python2.7/dist-packages/celery/local.py", line 188, in __call__
    return self._get_current_object()(*a, **kw)
  File "/usr/lib/python2.7/dist-packages/celery/app/task.py", line 420, in __call__
    return self.run(*args, **kwargs)
  File "/opt/OpenvStorage/ovs/lib/healthcheck.py", line 108, in execute_check
    HealthCheckController.check_volumedriver(logger)
  File "/usr/lib/python2.7/dist-packages/celery/local.py", line 188, in __call__
    return self._get_current_object()(*a, **kw)
  File "/usr/lib/python2.7/dist-packages/celery/app/task.py", line 420, in __call__
    return self.run(*args, **kwargs)
  File "/opt/OpenvStorage/ovs/lib/healthcheck.py", line 179, in check_volumedriver
    VolumedriverHealthCheck.run(logger)
  File "/opt/OpenvStorage/ovs/extensions/healthcheck/volumedriver/volumedriver_health_check.py", line 175, in run
    VolumedriverHealthCheck.check_dtl(logger)
  File "/opt/OpenvStorage/ovs/extensions/healthcheck/volumedriver/volumedriver_health_check.py", line 50, in check_dtl
    vdisk = VDiskHelper.get_vdisk_by_guid(vdisk_guid)
  File "/opt/OpenvStorage/ovs/extensions/healthcheck/helpers/vdisk.py", line 66, in get_vdisk_by_guid
    return VDisk(vdisk_guid)
  File "/opt/OpenvStorage/ovs/dal/hybrids/vdisk.py", line 65, in __init__
    DataObject.__init__(self, *args, **kwargs)
  File "/opt/OpenvStorage/ovs/dal/dataobject.py", line 233, in __init__
    self.__class__.__name__, self._guid
ovs.dal.exceptions.ObjectNotFoundException: VDisk with guid 'ffdd133a-1635-4255-955a-ba0bd0a49b8f' could not be found
```

### Setup
- Hyperconverged

### Packages
```
root@ovs-node03-1604:~# dpkg -l | grep openvstorage
ii  blktap-openvstorage-utils            2.0.90-2ubuntu4                     amd64        utilities to work with VHD disk images files
ii  libblktapctl0-openvstorage           2.0.90-2ubuntu4                     amd64        Xen API blktapctl shared library (shared library)
ii  libvhd0-openvstorage                 2.0.90-2ubuntu4                     amd64        VHD file format access library
ii  libvhdio-2.0.90-openvstorage         2.0.90-2ubuntu4                     amd64        Xen API blktap shared library (shared library)
ii  openvstorage                         2.7.7-rev.4367.d7725ca-1            amd64        openvStorage
ii  openvstorage-backend                 1.7.7-rev.828.5e3746c-1             amd64        openvStorage Backend plugin
ii  openvstorage-backend-core            1.7.7-rev.828.5e3746c-1             amd64        openvStorage Backend plugin core
ii  openvstorage-backend-webapps         1.7.7-rev.828.5e3746c-1             amd64        openvStorage Backend plugin Web Applications
ii  openvstorage-core                    2.7.7-rev.4367.d7725ca-1            amd64        openvStorage core
ii  openvstorage-hc                      1.7.7-rev.828.5e3746c-1             amd64        openvStorage Backend plugin HyperConverged
ii  openvstorage-health-check            3.1.2-rev.276.b629c81-1             amd64        Open vStorage HealthCheck
ii  openvstorage-sdm                     1.6.7-rev.455.7913d38-1             amd64        Open vStorage Backend ASD Manager
ii  openvstorage-webapps                 2.7.7-rev.4367.d7725ca-1            amd64        openvStorage Web Applications
```

**Comment by kinvaris** [comment]
https://github.com/openvstorage/openvstorage-health-check/pull/173

**Comment by wimpers** [comment]
@kinvaris how can this be a race condition? Could you elaborate?

**Comment by kinvaris** [comment]
Its a race condition in the healthcheck, the `check_volumedrivers` method and `check_dtl` method are executed to rapidly. So its possible that the framework still has some old properties cached as we execute `check_dtl`. This is why we are introducing the ignore (for outside protection) and avoid.

**Comment by wimpers** [comment]
@kinvaris you mean info of disk you created during the healthcheck run?

**Comment by kinvaris** [comment]
@wimpers yes during the `check_volumedrivers` we create & delete a vdisk to verify that the volumedriver is still working fine. In some cases (if the next code is going to fast), this can cause problems like in the main description.

See also my `possible root of problem`: `because sometimes it happens sometimes it does not happen`

**Comment by wimpers** [comment]
So you switched the check of the create vdisk and DTL so the DTL check can't fall over newly created disk. Got it.

**Comment by JeffreyDevloo** [comment]
Fixed by https://github.com/openvstorage/openvstorage-health-check/pull/173

**Comment by kinvaris** [comment]
Found another issue because not properly tested.
```
2016-11-30 11:19:52 49000 +0100 - ovs-node01-1604 - 10600/140638994228992 - healthcheck/logger - 150 - ERROR - Test: None - Error during execution of the healthcheck
Traceback (most recent call last):
  File "/opt/OpenvStorage/ovs/lib/healthcheck.py", line 109, in execute_check
    HealthCheckController._check_volumedriver(logger)
  File "/usr/lib/python2.7/dist-packages/celery/local.py", line 188, in __call__
    return self._get_current_object()(*a, **kw)
  File "/usr/lib/python2.7/dist-packages/celery/app/task.py", line 420, in __call__
    return self.run(*args, **kwargs)
  File "/opt/OpenvStorage/ovs/lib/healthcheck.py", line 183, in _check_volumedriver
    VolumedriverHealthCheck.run(logger)
  File "/opt/OpenvStorage/ovs/extensions/healthcheck/volumedriver/volumedriver_health_check.py", line 181, in run
    VolumedriverHealthCheck.check_dtl(logger)
  File "/opt/OpenvStorage/ovs/extensions/healthcheck/volumedriver/volumedriver_health_check.py", line 59, in check_dtl
    dtl_status = vdisk.dtl_status
UnboundLocalError: local variable 'vdisk' referenced before assignment

```

**Comment by kinvaris** [comment]
Should be fixed by https://github.com/openvstorage/openvstorage-health-check/pull/182/files
