### ISSUE TITLE
TypeError: run() got an unexpected keyword argument 'host'

### ISSUE THREAD

**Issue by kinvaris** [openvstorage/openvstorage-health-check#190]
## Problem description
Seen during our nightly builds.

### Logs
```
[INFO] Starting Alba Health Check!
[INFO] ===========================
[INFO] Checking available ALBA backends ...
[SUCCESS] No problems occured when fetching alba backends!
[SUCCESS] We found 3 backend(s)!
[INFO] Checking the ALBA proxies ...
[INFO] Checking ALBA proxy 'albaproxy_myvpool01': 
[EXCEPTION] Error during execution of the healthcheck
Traceback (most recent call last):
  File "/opt/OpenvStorage/ovs/lib/healthcheck.py", line 35, in <module>
    class HealthCheckController(object):
  File "/opt/OpenvStorage/ovs/lib/healthcheck.py", line 419, in HealthCheckController
    HealthCheckController.run_method(*arguments)
  File "/opt/OpenvStorage/ovs/lib/healthcheck.py", line 367, in run_method
    return HealthCheckController.check_attended()
  File "/usr/lib/python2.7/dist-packages/celery/local.py", line 188, in __call__
    return self._get_current_object()(*a, **kw)
  File "/usr/lib/python2.7/dist-packages/celery/app/task.py", line 420, in __call__
    return self.run(*args, **kwargs)
  File "/opt/OpenvStorage/ovs/lib/healthcheck.py", line 70, in check_attended
    return HealthCheckController.execute_check(unattended, silent_mode)
  File "/usr/lib/python2.7/dist-packages/celery/local.py", line 188, in __call__
    return self._get_current_object()(*a, **kw)
  File "/usr/lib/python2.7/dist-packages/celery/app/task.py", line 420, in __call__
    return self.run(*args, **kwargs)
  File "/opt/OpenvStorage/ovs/lib/healthcheck.py", line 111, in execute_check
    HealthCheckController._check_alba(logger)
  File "/usr/lib/python2.7/dist-packages/celery/local.py", line 188, in __call__
    return self._get_current_object()(*a, **kw)
  File "/usr/lib/python2.7/dist-packages/celery/app/task.py", line 420, in __call__
    return self.run(*args, **kwargs)
  File "/opt/OpenvStorage/ovs/lib/healthcheck.py", line 167, in _check_alba
    AlbaHealthCheck.run(logger)
  File "/opt/OpenvStorage/ovs/extensions/healthcheck/alba/alba_health_check.py", line 546, in run
    AlbaHealthCheck.check_alba(logger)
  File "/opt/OpenvStorage/ovs/extensions/healthcheck/alba/alba_health_check.py", line 347, in check_alba
    AlbaHealthCheck.check_if_proxies_work(logger)
  File "/opt/OpenvStorage/ovs/extensions/healthcheck/alba/alba_health_check.py", line 146, in check_if_proxies_work
    proxy_client_cfg = AlbaCLI.run('proxy-client-cfg', host=ip, port=service.ports[0])
TypeError: run() got an unexpected keyword argument 'host'
```

### Setup
- Hyperconverged

### Packages
// List packages in the code tags using dpkg -l | grep openvstorage
```
ii  blktap-openvstorage-utils            2.0.90-2ubuntu4                     amd64        utilities to work with VHD disk images files
ii  libblktapctl0-openvstorage           2.0.90-2ubuntu4                     amd64        Xen API blktapctl shared library (shared library)
ii  libvhd0-openvstorage                 2.0.90-2ubuntu4                     amd64        VHD file format access library
ii  libvhdio-2.0.90-openvstorage         2.0.90-2ubuntu4                     amd64        Xen API blktap shared library (shared library)
ii  openvstorage                         2.7.7-rev.4379.c7a85f0-1            amd64        openvStorage
ii  openvstorage-backend                 1.7.7-rev.844.358139f-1             amd64        openvStorage Backend plugin
ii  openvstorage-backend-core            1.7.7-rev.844.358139f-1             amd64        openvStorage Backend plugin core
ii  openvstorage-backend-webapps         1.7.7-rev.844.358139f-1             amd64        openvStorage Backend plugin Web Applications
ii  openvstorage-core                    2.7.7-rev.4379.c7a85f0-1            amd64        openvStorage core
ii  openvstorage-hc                      1.7.7-rev.844.358139f-1             amd64        openvStorage Backend plugin HyperConverged
ii  openvstorage-health-check            3.1.2-rev.287.24f22eb-1             amd64        Open vStorage HealthCheck
ii  openvstorage-sdm                     1.6.7-rev.476.3674990-1             amd64        Open vStorage Backend ASD Manager
ii  openvstorage-webapps                 2.7.7-rev.4379.c7a85f0-1            amd64        openvStorage Web Applications
```

**Comment by kinvaris** [comment]
We tried to properly fix this with the new `AlbaCLI.run` implementation but it seems like were are blocked on this ticket: https://github.com/openvstorage/alba/issues/473

**Comment by kinvaris** [comment]
@JeffreyDevloo apparently the new alba package is released, please test this with the dev branch https://github.com/openvstorage/openvstorage-health-check/tree/fix-alba-cli

**Comment by JeffreyDevloo** [comment]
Should be fixed by https://github.com/openvstorage/openvstorage-health-check/pull/192

**Comment by kinvaris** [comment]
PASSED as we don't see this happening in the CI tests anymore.
