### ISSUE TITLE
Error when calling alba check.

### ISSUE THREAD

**Issue by grimpy** [openvstorage/openvstorage-health-check#212]
Jo De Boeck, [14.12.16 14:04]

```
2016-12-14 13:03:16 50100 +0100 - stor-01.du-conv-3 - 6933/139655518824256 - extensions/alba-cli - 147 - DEBUG - stdout: {"success":false,"error":{"message":"(Unix.Unix_error \"Connection refused\" connect \"\")","exception_type":"unknown","exception_code":0}}

Traceback (most recent call last):
~   File "ovs_healthcheck.py", line 78, in <module>
    print(yaml.dump(action(), default_flow_style=False))
~   File "ovs_healthcheck.py", line 72, in action
    alba.run(logger)
~   File "/opt/OpenvStorage/ovs/extensions/healthcheck/alba/alba_health_check.py", line 672, in run
    AlbaHealthCheck.check_backends(logger)
~   File "/opt/OpenvStorage/ovs/extensions/healthcheck/alba/alba_health_check.py", line 459, in check_backends
    backend.get('name'))
~   File "/opt/OpenvStorage/ovs/extensions/healthcheck/alba/alba_health_check.py", line 382, in check_backend_asds
    extra_params=[key, value])
~   File "/opt/OpenvStorage/ovs/extensions/healthcheck/helpers/albacli.py", line 156, in run
    raise RuntimeError(output['error']['message'])
~ RuntimeError: (Unix.Unix_error "Connection refused" connect "")

type/level: UNKNOWN/1
RuntimeError: (Unix.Unix_error "Connection refused" connect "")

```

**Comment by JeffreyDevloo** [comment]
Fixed by https://github.com/openvstorage/openvstorage-health-check/pull/214.
