### ISSUE TITLE
healthcheck stuck at `Checking RabbitMQ/Celery port`

### ISSUE THREAD

**Issue by kinvaris** [openvstorage/openvstorage-health-check#215]
## Problem description
The check of RabbitMQ/celery port check is stuck for a long time

### Logs
```
[INFO] Checking RabbitMQ/Celery ...
^C[EXCEPTION] Error during execution of the healthcheck
Traceback (most recent call last):
  File "/opt/OpenvStorage/ovs/lib/healthcheck.py", line 35, in <module>
    class HealthCheckController(object):
  File "/opt/OpenvStorage/ovs/lib/healthcheck.py", line 419, in HealthCheckController
    HealthCheckController.run_method(*arguments)
  File "/opt/OpenvStorage/ovs/lib/healthcheck.py", line 367, in run_method
    return HealthCheckController.check_attended()
  File "/usr/lib/python2.7/dist-packages/celery/local.py", line 188, in __call__
    return self._get_current_object()(*a, **kw)
  File "/usr/lib/python2.7/dist-packages/celery/app/task.py", line 420, in __call__
    return self.run(*args, **kwargs)
  File "/opt/OpenvStorage/ovs/lib/healthcheck.py", line 70, in check_attended
    return HealthCheckController.execute_check(unattended, silent_mode)
  File "/usr/lib/python2.7/dist-packages/celery/local.py", line 188, in __call__
    return self._get_current_object()(*a, **kw)
  File "/usr/lib/python2.7/dist-packages/celery/app/task.py", line 420, in __call__
    return self.run(*args, **kwargs)
  File "/opt/OpenvStorage/ovs/lib/healthcheck.py", line 108, in execute_check
    HealthCheckController._check_openvstorage(logger)
  File "/usr/lib/python2.7/dist-packages/celery/local.py", line 188, in __call__
    return self._get_current_object()(*a, **kw)
  File "/usr/lib/python2.7/dist-packages/celery/app/task.py", line 420, in __call__
    return self.run(*args, **kwargs)
  File "/opt/OpenvStorage/ovs/lib/healthcheck.py", line 135, in _check_openvstorage
    OpenvStorageHealthCheck.run(logger)
  File "/opt/OpenvStorage/ovs/extensions/healthcheck/openvstorage/openvstoragecluster_health_check.py", line 576, in run
    OpenvStorageHealthCheck.check_required_ports(logger)
  File "/opt/OpenvStorage/ovs/extensions/healthcheck/openvstorage/openvstoragecluster_health_check.py", line 231, in check_required_ports
    pcel = commands.getoutput(pcommand.format(pcommand)).split("\n")
  File "/usr/lib/python2.7/commands.py", line 50, in getoutput
    return getstatusoutput(cmd)[1]
  File "/usr/lib/python2.7/commands.py", line 60, in getstatusoutput
    text = pipe.read()
KeyboardInterrupt
root@ovs-node01-1604:~# 

```

## Possible solution
Add a timeout to the call

### Setup
- Hyperconverged

### Packages
```
ii  blktap-openvstorage-utils            2.0.90-2ubuntu4                     amd64        utilities to work with VHD disk images files
ii  libblktapctl0-openvstorage           2.0.90-2ubuntu4                     amd64        Xen API blktapctl shared library (shared library)
ii  libvhd0-openvstorage                 2.0.90-2ubuntu4                     amd64        VHD file format access library
ii  libvhdio-2.0.90-openvstorage         2.0.90-2ubuntu4                     amd64        Xen API blktap shared library (shared library)
ii  openvstorage                         2.7.8-rev.4433.ad64456-1            amd64        openvStorage
ii  openvstorage-backend                 1.7.8-rev.873.16660bb-1             amd64        openvStorage Backend plugin
ii  openvstorage-backend-core            1.7.8-rev.873.16660bb-1             amd64        openvStorage Backend plugin core
ii  openvstorage-backend-webapps         1.7.8-rev.873.16660bb-1             amd64        openvStorage Backend plugin Web Applications
ii  openvstorage-core                    2.7.8-rev.4433.ad64456-1            amd64        openvStorage core
ii  openvstorage-hc                      1.7.8-rev.873.16660bb-1             amd64        openvStorage Backend plugin HyperConverged
ii  openvstorage-health-check            3.1.2-rev.346.13d0922-1             amd64        Open vStorage HealthCheck
ii  openvstorage-sdm                     1.6.8-rev.495.135932c-1             amd64        Open vStorage Backend ASD Manager
ii  openvstorage-webapps                 2.7.8-rev.4433.ad64456-1            amd64        openvStorage Web Applications
```

**Comment by wimpers** [comment]
Any idea why the RabiitMQ was stuck? Can we find the root cause?

**Comment by kinvaris** [comment]
This was on a CI environment where I let the root partition drown in 0% free space.
Under those conditions the healthcheck should still be able to perform. This is how I triggered the given result.
