### ISSUE TITLE
Issue in health check with missing vdisk

### ISSUE THREAD

**Issue by wimpers** [openvstorage/openvstorage-health-check#233]
```
[EXCEPTION] Error during execution of the healthcheck
Traceback (most recent call last):
  File "/opt/OpenvStorage/ovs/lib/healthcheck.py", line 35, in <module>
    class HealthCheckController(object):
  File "/opt/OpenvStorage/ovs/lib/healthcheck.py", line 419, in HealthCheckController
    HealthCheckController.run_method(*arguments)
  File "/opt/OpenvStorage/ovs/lib/healthcheck.py", line 367, in run_method
    return HealthCheckController.check_attended()
  File "/usr/lib/python2.7/dist-packages/celery/local.py", line 188, in __call__
    return self._get_current_object()(*a, **kw)
  File "/usr/lib/python2.7/dist-packages/celery/app/task.py", line 420, in __call__
    return self.run(*args, **kwargs)
  File "/opt/OpenvStorage/ovs/lib/healthcheck.py", line 70, in check_attended
    return HealthCheckController.execute_check(unattended, silent_mode)
  File "/usr/lib/python2.7/dist-packages/celery/local.py", line 188, in __call__
    return self._get_current_object()(*a, **kw)
  File "/usr/lib/python2.7/dist-packages/celery/app/task.py", line 420, in __call__
    return self.run(*args, **kwargs)
  File "/opt/OpenvStorage/ovs/lib/healthcheck.py", line 109, in execute_check
    HealthCheckController._check_volumedriver(logger)
  File "/usr/lib/python2.7/dist-packages/celery/local.py", line 188, in __call__
    return self._get_current_object()(*a, **kw)
  File "/usr/lib/python2.7/dist-packages/celery/app/task.py", line 420, in __call__
    return self.run(*args, **kwargs)
  File "/opt/OpenvStorage/ovs/lib/healthcheck.py", line 183, in _check_volumedriver
    VolumedriverHealthCheck.run(logger)
  File "/opt/OpenvStorage/ovs/extensions/healthcheck/volumedriver/volumedriver_health_check.py", line 400, in run
    VolumedriverHealthCheck.check_dtl(logger)
  File "/opt/OpenvStorage/ovs/extensions/healthcheck/volumedriver/volumedriver_health_check.py", line 63, in check_dtl
    results = VolumedriverHealthCheck._check_disk_dtl(vdisk_guid=vdisk_guid)
  File "/usr/local/lib/python2.7/dist-packages/timeout_decorator/timeout_decorator.py", line 69, in new_function
    return function(*args, **kwargs)
  File "/opt/OpenvStorage/ovs/extensions/healthcheck/volumedriver/volumedriver_health_check.py", line 93, in _check_disk_dtl
    vdisk = VDiskHelper.get_vdisk_by_guid(vdisk_guid)
  File "/opt/OpenvStorage/ovs/extensions/healthcheck/helpers/vdisk.py", line 66, in get_vdisk_by_guid
    return VDisk(vdisk_guid)
  File "/opt/OpenvStorage/ovs/dal/hybrids/vdisk.py", line 65, in __init__
    DataObject.__init__(self, *args, **kwargs)
  File "/opt/OpenvStorage/ovs/dal/dataobject.py", line 233, in __init__
    self.__class__.__name__, self._guid
ovs.dal.exceptions.ObjectNotFoundException: VDisk with guid '0bc46929-008c-4883-845d-23133af8038a' could not be found
root@pocops-ovs03:~#
```

**Comment by wimpers** [comment]
* No disks were removed (except health check disks)
* At least we should capture the error and move on

**Comment by JeffreyDevloo** [comment]
Might have been a remnant of the volumedriver check (which creates a vdisk)

**Comment by JeffreyDevloo** [comment]
https://github.com/openvstorage/openvstorage-health-check/pull/242
