### ISSUE TITLE
Crash when /etc/apt/sources.list.d/ovsaptrepo.list does not exist.

### ISSUE THREAD

**Issue by grimpy** [openvstorage/openvstorage-health-check#250]
Should give error message not crash the entire script

![161231_185007](https://cloud.githubusercontent.com/assets/143869/21578476/26a13e08-cf8a-11e6-8c54-50731975b297.png)

**Comment by jeroenmaelbrancke** [comment]
Still an issue in the latest unstable version.

```
root@pocops-voldrv02:/opt/OpenvStorage/ovs# python /opt/OpenvStorage/ovs/lib/healthcheck.py X X
Traceback (most recent call last):
  File "/opt/OpenvStorage/ovs/lib/healthcheck.py", line 27, in <module>
    HealthCheckCLIRunner.run_method(*arguments)
  File "/opt/OpenvStorage/ovs/extensions/healthcheck/expose_to_cli.py", line 271, in run_method
  File "/opt/OpenvStorage/ovs/extensions/healthcheck/helpers/helper.py", line 74, in get_local_settings
  File "/opt/OpenvStorage/ovs/extensions/healthcheck/helpers/helper.py", line 96, in get_ovs_version
IOError: [Errno 2] No such file or directory: '/etc/apt/sources.list.d/ovsaptrepo.list'
```

**Comment by JeffreyDevloo** [comment]
https://github.com/openvstorage/openvstorage-health-check/pull/268
