### ISSUE TITLE
Exception in halted volumes when volume is detached/unreachable

### ISSUE THREAD

**Issue by matthiasdeblock** [openvstorage/openvstorage-health-check#26]
```
[INFO] Checking vPool 'env1newvpool': 
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python2.7/dist-packages/celery/local.py", line 167, in <lambda>
    __call__ = lambda x, *a, **kw: x._get_current_object()(*a, **kw)
  File "/usr/lib/python2.7/dist-packages/celery/app/task.py", line 420, in __call__
    return self.run(*args, **kwargs)
  File "healthcheck.py", line 85, in check_attended
    return HealthCheckController.execute_check()
  File "/usr/lib/python2.7/dist-packages/celery/local.py", line 167, in <lambda>
    __call__ = lambda x, *a, **kw: x._get_current_object()(*a, **kw)
  File "/usr/lib/python2.7/dist-packages/celery/app/task.py", line 420, in __call__
    return self.run(*args, **kwargs)
  File "healthcheck.py", line 132, in execute_check
    HealthCheckController.check_openvstorage()
  File "/usr/lib/python2.7/dist-packages/celery/local.py", line 167, in <lambda>
    __call__ = lambda x, *a, **kw: x._get_current_object()(*a, **kw)
  File "/usr/lib/python2.7/dist-packages/celery/app/task.py", line 420, in __call__
    return self.run(*args, **kwargs)
  File "healthcheck.py", line 185, in check_openvstorage
    ovs.check_for_halted_volumes()
  File "/opt/OpenvStorage/ovs/extensions/healthcheck/openvstorage/openvstoragecluster_health_check.py", line 947, in check_for_halted_volumes
    if int(self.utility.convert_xml_to_json(voldrv_client.info_volume(volume))["boost_serialization"]
volumedriver.storagerouter.storagerouterclient.MaxRedirectsExceededException: volumeInfo 
```

**Comment by kinvaris** [comment]
#32
