### ISSUE TITLE
RuntimeError: Client_helper.MasterLookupResult.Error(0)

### ISSUE THREAD

**Issue by jeroenmaelbrancke** [openvstorage/openvstorage-health-check#279]
## Problem description
The albabackends failed with a runtime error.
The healthcheck must work at all cost and should check the other checks also.

issue alba: https://github.com/openvstorage/alba/issues/608

```
[INFO] Checking available ALBA backends.
Traceback (most recent call last):
  File "/opt/OpenvStorage/ovs/lib/healthcheck.py", line 27, in <module>
    HealthCheckCLIRunner.run_method(*arguments)
  File "/opt/OpenvStorage/ovs/extensions/healthcheck/expose_to_cli.py", line 279, in run_method
    found_method(result_handler.HCResultCollector(result=result_handler, test_name=test_name))
  File "/opt/OpenvStorage/ovs/extensions/healthcheck/alba/alba_health_check.py", line 352, in check_backends
    alba_backends = AlbaHealthCheck._get_all_responding_backends(result_handler)
  File "/opt/OpenvStorage/ovs/extensions/healthcheck/alba/alba_health_check.py", line 304, in _get_all_responding_backends
    for preset in alba_backend.presets:
  File "/opt/OpenvStorage/ovs/dal/dataobject.py", line 344, in <lambda>
    fget = lambda s: s._get_dynamic_property(dynamic)
  File "/opt/OpenvStorage/ovs/dal/dataobject.py", line 413, in _get_dynamic_property
    return self._backend_property(data_loader, dynamic)
  File "/opt/OpenvStorage/ovs/dal/dataobject.py", line 1003, in _backend_property
    dynamic_data = function()
  File "/opt/OpenvStorage/ovs/dal/hybrids/albabackend.py", line 254, in _presets
    for disk in self.local_stack[node.node_id].values():
  File "/opt/OpenvStorage/ovs/dal/dataobject.py", line 344, in <lambda>
    fget = lambda s: s._get_dynamic_property(dynamic)
  File "/opt/OpenvStorage/ovs/dal/dataobject.py", line 413, in _get_dynamic_property
    return self._backend_property(data_loader, dynamic)
  File "/opt/OpenvStorage/ovs/dal/dataobject.py", line 1003, in _backend_property
    dynamic_data = function()
  File "/opt/OpenvStorage/ovs/dal/hybrids/albabackend.py", line 142, in _local_stack
    for found_osd in AlbaCLI.run(command='list-all-osds', config=config):
  File "/opt/OpenvStorage/ovs/extensions/plugins/albacli.py", line 127, in run
    raise RuntimeError(output['error']['message'])
RuntimeError: Client_helper.MasterLookupResult.Error(0)
```

### Packages
```
root@stor-01:~# dpkg -l | grep openvstorage
ii  openvstorage                         2.7.10.1-1                              amd64        openvStorage
ii  openvstorage-backend                 1.7.10.1-1                              amd64        openvStorage Backend plugin
ii  openvstorage-backend-core            1.7.10.1-1                              amd64        openvStorage Backend plugin core
ii  openvstorage-backend-webapps         1.7.10.1-1                              amd64        openvStorage Backend plugin Web Applications
ii  openvstorage-core                    2.7.10.1-1                              amd64        openvStorage core
ii  openvstorage-hc                      1.7.10.1-1                              amd64        openvStorage Backend plugin HyperConverged
ii  openvstorage-health-check            3.2.0-fargo.2-1                         amd64        Open vStorage HealthCheck
ii  openvstorage-sdm                     1.6.10.1-1                              amd64        Open vStorage Backend ASD Manager
ii  openvstorage-webapps                 2.7.10.1-1                              amd64        openvStorage Web Applications

```

**Comment by JeffreyDevloo** [comment]
Alright, we should catch these errors aswell. Localstack fetches info from alba which in turn fetches it from Arakoons.

**Comment by JeffreyDevloo** [comment]
Fixed by https://github.com/openvstorage/openvstorage-health-check/pull/290
