### ISSUE TITLE
Output proper output errors

### ISSUE THREAD

**Issue by kinvaris** [openvstorage/openvstorage-health-check#281]
I tried `ovs healthcheck help` and got this message:
```
Traceback (most recent call last):
  File "/opt/OpenvStorage/ovs/lib/healthcheck.py", line 27, in <module>
    HealthCheckCLIRunner.run_method(*arguments)
  File "/opt/OpenvStorage/ovs/extensions/healthcheck/expose_to_cli.py", line 267, in run_method
    found_method_pointers = HealthCheckCLIRunner._get_methods(module_name, method_name, HealthCheckCLIRunner.ADDON_TYPE)
  File "/opt/OpenvStorage/ovs/extensions/healthcheck/expose_to_cli.py", line 70, in _get_methods
    for function_data in discovered_data[module_name]:
KeyError: 'help'
```

This should be caught and properly given a stderr message

**Comment by JeffreyDevloo** [comment]
Fixed by https://github.com/openvstorage/openvstorage-health-check/pull/294
