### ISSUE TITLE
CheckModelConsistency fails when volumedriver is down

### ISSUE THREAD

**Issue by kinvaris** [openvstorage/openvstorage-health-check#29]
```
[INFO] Checking DNS resolving: 
[SUCCESS] DNS resolving works!

[INFO] Checking model consistency: 
[INFO] Precheck: verification of RabbitMQ cluster: 
[SUCCESS] RabbitMQ does not seem to have 'partition' problems :D
[INFO] Checking consistency of volumedriver vs. ovsdb for vPool 'vmstor': 
Traceback (most recent call last):
  File "ovs_health_check/main.py", line 116, in <module>
    Main(unattended)
  File "ovs_health_check/main.py", line 73, in __init__
    self.ovs.checkModelConsistency()
  File "/opt/openvstorage-health-check/openvstorage/openvstoragecluster_health_check.py", line 663, in checkModelConsistency
    voldrv_volume_list = voldrv_client.list_volumes()
volumedriver.storagerouter.storagerouterclient.ClusterNotReachableException:  
```

**Comment by kinvaris** [comment]
Should just be:
`from volumedriver.storagerouter.storagerouterclient import ClusterNotReachableException`
and then catch it on line:
`https://github.com/openvstorage/openvstorage-health-check/blob/ovs-impl/ovs/extensions/healthcheck/openvstorage/openvstoragecluster_health_check.py#L890`
and 
`https://github.com/openvstorage/openvstorage-health-check/blob/ovs-impl/ovs/extensions/healthcheck/openvstorage/openvstoragecluster_health_check.py#L944`

**Comment by jeroenmaelbrancke** [comment]
Added extra ssd to the servers, Setup new ovs cluster, Tested the code (5h)
