### ISSUE TITLE
Healthcheck cannot run without ovs version

### ISSUE THREAD

**Issue by JeffreyDevloo** [openvstorage/openvstorage-health-check#322]
## Problem description
Removal of the ovs version from the framework results in the healthcheck not working.
```
root@ovs-node01-1604:~# ovs healthcheck
Traceback (most recent call last):
  File "/opt/OpenvStorage/ovs/lib/healthcheck.py", line 26, in <module>
    HealthCheckCLIRunner.run_method(*arguments)
  File "/opt/OpenvStorage/ovs/extensions/healthcheck/expose_to_cli.py", line 306, in run_method
    local_settings = Helper.get_local_settings()
  File "/opt/OpenvStorage/ovs/extensions/healthcheck/helpers/helper.py", line 80, in get_local_settings
    'environment_release': Helper.get_ovs_release_name(),
  File "/opt/OpenvStorage/ovs/extensions/healthcheck/helpers/helper.py", line 96, in get_ovs_release_name
    release_name = json.load(ovs_json)["support"]["release_name"]
KeyError: 'release_name'
```
## Packages
openvstorage-health-check            3.2.2-1

**Comment by JeffreyDevloo** [comment]
Fixed by https://github.com/openvstorage/openvstorage-health-check/pull/323/commits/fbdba60d8574d7c43278ce81acc1e5fc0a7ccc32
