### ISSUE TITLE
failed to retrieve config from etcd during healthcheck

### ISSUE THREAD

**Issue by jeroenmaelbrancke** [openvstorage/openvstorage-health-check#33]
```
[INFO] Checking consistency of volumedriver vs. ovsdb for vPool 'beops-vpool-b': 
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python2.7/dist-packages/celery/local.py", line 167, in <lambda>
    __call__ = lambda x, *a, **kw: x._get_current_object()(*a, **kw)
  File "/usr/lib/python2.7/dist-packages/celery/app/task.py", line 420, in __call__
    return self.run(*args, **kwargs)
  File "healthcheck.py", line 85, in check_attended
    return HealthCheckController.execute_check()
  File "/usr/lib/python2.7/dist-packages/celery/local.py", line 167, in <lambda>
    __call__ = lambda x, *a, **kw: x._get_current_object()(*a, **kw)
  File "/usr/lib/python2.7/dist-packages/celery/app/task.py", line 420, in __call__
    return self.run(*args, **kwargs)
  File "healthcheck.py", line 132, in execute_check
    HealthCheckController.check_openvstorage()
  File "/usr/lib/python2.7/dist-packages/celery/local.py", line 167, in <lambda>
    __call__ = lambda x, *a, **kw: x._get_current_object()(*a, **kw)
  File "/usr/lib/python2.7/dist-packages/celery/app/task.py", line 420, in __call__
    return self.run(*args, **kwargs)
  File "healthcheck.py", line 182, in check_openvstorage
    ovs.check_model_consistency()
  File "/opt/OpenvStorage/ovs/extensions/healthcheck/openvstorage/openvstoragecluster_health_check.py", line 887, in check_model_consistency
    voldrv_client = src.LocalStorageRouterClient(config_file)
RuntimeError: Failed to retrieve config from etcd 
```

**Comment by kinvaris** [comment]
The ETCD part of the healthcheck in this repo will be removed. Because this healthcheck will only serve a purpose for `eugene-updates`.
