### ISSUE TITLE
remove module from ovs-impl

### ISSUE THREAD

**Issue by matthiasdeblock** [openvstorage/openvstorage-health-check#36]
Please remove the module  "from ovs.extensions.db.arakoon.arakoon.ArakoonManagement import ArakoonManagementEx" from /opt/OpenvStorage/ovs/extensions/healthcheck/arakoon/arakooncluster_health_check.py

----
root@ovs02:~/openvstorage-health-check# ovs healthcheck
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "healthcheck.py", line 23, in <module>
    from ovs.extensions.healthcheck.arakoon.arakooncluster_health_check import ArakoonHealthCheck
  File "/opt/OpenvStorage/ovs/extensions/healthcheck/arakoon/arakooncluster_health_check.py", line 26, in <module>
    from ovs.extensions.db.arakoon.arakoon.ArakoonManagement import ArakoonManagementEx
ImportError: No module named arakoon.ArakoonManagement

**Comment by matthiasdeblock** [comment]
Pull request approved.
