### ISSUE TITLE
Create support for extra nodes

### ISSUE THREAD

**Issue by kinvaris** [openvstorage/openvstorage-health-check#4]
Check if the script is running on master or extra nodes. Keep in mind:
* Celery / rabbitmq will not work here, so just skip

* Listing directories does not work:
```
[INFO] Checking if logfiles their size is not bigger than 500 MB: 
Traceback (most recent call last):
File "ovs_health_check/main.py", line 116, in <module>
Main(unattended)
File "ovs_health_check/main.py", line 69, in _init_
self.ovs.checkSizeOfLogFiles()
File "/opt/openvstorage-health-check/openvstorage/openvstoragecluster_health_check.py", line 136, in checkSizeOfLogFiles
nested_dirs = self._listDirsInDirectory(log)
File "/opt/openvstorage-health-check/openvstorage/openvstoragecluster_health_check.py", line 175, in _listDirsInDirectory
return next(os.walk(pwd))[1]
StopIteration
[16:07:37] Maxime Daniel: [FAILURE] Connection FAILED to service Celery, please check 'RabbitMQ' and 'ovs-workers'?
```

**Comment by kinvaris** [comment]
* Fixed the rabbitmq issue, was explicit extra/master problem
* Fixed the listing directories (if dir or file does not exists, it will just ignore it)
