### ISSUE TITLE
[develop] wrong import from moved toolbox

### ISSUE THREAD

**Issue by simonOpenV** [openvstorage/openvstorage-health-check#445]
## Problem description
Error keeps popping up in healthcheck cli runner

## Possible root of the problem
Toolbox has been moved to the extensionstoolbox

### Logs
```
ner/expose_to_cli.py - run_method - 7 - ERROR - Unhandled exception caught when executing check_if_proxie
s_work
Traceback (most recent call last):
  File "/opt/OpenvStorage/ovs/extensions/healthcheck/expose_to_cli.py", line 317, in run_method
    node_check(found_method)(result_handler.HCResultCollector(result=result_handler, test_name=test_name)
)  # Wrapped in nodecheck for callback
  File "/opt/OpenvStorage/ovs/extensions/healthcheck/decorators.py", line 52, in wrapped
    return func(*args, **kwargs)
  File "/opt/OpenvStorage/ovs/extensions/healthcheck/decorators.py", line 125, in wrapped
    return func(*args, **kwargs)
  File "/opt/OpenvStorage/ovs/extensions/healthcheck/alba_hc.py", line 272, in check_if_proxies_work
    Toolbox.verify_required_params(required_params=namespace_params, actual_params=namespace_info)
AttributeError: type object 'Toolbox' has no attribute 'verify_required_params'

```

**Comment by simonOpenV** [comment]
### Fixed by 
#444 
### Package information

openvstorage-test_3.4.1-dev.1519910301.6a3d552-1
--

**Comment by JeffreyDevloo** [comment]
Released in https://github.com/openvstorage/openvstorage-health-check/releases/tag/3.7.0
Packaged in openvstorage-health-check_3.7.0-1_amd64.deb
