### ISSUE TITLE
Catch subprocess.CalledProcessError

### ISSUE THREAD

**Issue by kinvaris** [openvstorage/openvstorage-health-check#58]
```
2016-06-29 17:46:54 639267 +0200 - ctrl-roub-01 - 11787/0 - alba/cli - 0 - warning - Networking2.ConnectTimeoutalba: internal error, uncaught exception:
      Networking2.ConnectTimeout
      Raised at file "src/core/lwt.ml", line 789, characters 22-23
      Called from file "src/unix/lwt_main.ml", line 34, characters 8-18
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/celery/local.py", line 188, in __call__
    return self._get_current_object()(*a, **kw)
  File "/usr/local/lib/python2.7/dist-packages/celery/app/task.py", line 420, in __call__
    return self.run(*args, **kwargs)
  File "healthcheck.py", line 88, in check_attended
    return HealthCheckController.execute_check()
  File "/usr/local/lib/python2.7/dist-packages/celery/local.py", line 188, in __call__
    return self._get_current_object()(*a, **kw)
  File "/usr/local/lib/python2.7/dist-packages/celery/app/task.py", line 420, in __call__
    return self.run(*args, **kwargs)
  File "healthcheck.py", line 137, in execute_check
    HealthCheckController.check_alba()
  File "/usr/local/lib/python2.7/dist-packages/celery/local.py", line 188, in __call__
    return self._get_current_object()(*a, **kw)
  File "/usr/local/lib/python2.7/dist-packages/celery/app/task.py", line 420, in __call__
    return self.run(*args, **kwargs)
  File "healthcheck.py", line 223, in check_alba
    alba.check_alba()
  File "/opt/OpenvStorage/ovs/extensions/healthcheck/alba/alba_health_check.py", line 356, in check_alba
    result_disks = self._check_backend_asds(backend.get('all_disks'), backend.get('name'))
  File "/opt/OpenvStorage/ovs/extensions/healthcheck/alba/alba_health_check.py", line 311, in _check_backend_asds
    str(disk.get('port')), '-h', ip_address, key])
  File "/usr/lib/python2.7/subprocess.py", line 573, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['alba', 'asd-delete', '--long-id', u'A1P2oX2aPJi3H11AspmC8hRJgABTcfws', '-p', '8607', '-h', u'5.196.86.94', 'ovs-healthcheck-fe50ba20-f526-4c92-bcd2-7b506ea1b4a7']' returned non-zero exit status 1
```

**Comment by kinvaris** [comment]
This has been fixed because we use the AlbaCLi from the framework.
