### ISSUE TITLE
Healthcheck does not work on fargo based environment

### ISSUE THREAD

**Issue by grimpy** [openvstorage/openvstorage-health-check#65]
```
root@ovs-01:~# jspython ovs_healthcheck.py
Traceback (most recent call last):
~   File "ovs_healthcheck.py", line 80, in <module>
    print action()
~   File "ovs_healthcheck.py", line 31, in action
    from ovs.extensions.healthcheck.openvstorage.openvstoragecluster_health_check import OpenvStorageHealthCheck
~   File "/opt/OpenvStorage/ovs/extensions/healthcheck/openvstorage/openvstoragecluster_health_check.py", line 37, in <module>
    from ovs.dal.lists.pmachinelist import PMachineList
~ ImportError: No module named pmachinelist
```

pmachinelist has been removed on fargo

**Comment by kinvaris** [comment]
Will try to fix this today

**Comment by kinvaris** [comment]
Pull request #70 is merged, this problem should be fixed.
